In [1]:
import pandas as pd
import numpy as np
mortality = pd.read_csv(r'../data/mortality/mortality_cleaned.csv')

In [2]:
drought_3year = pd.read_csv(r'../data/drought_monitor/drought_indicator_3year_matrics_reformat.csv')
drought_3year.head()

    GISJOIN  year  drought_3year
0  G0100010  2016       0.000000
1  G0100010  2015       0.666487
2  G0100010  2014       6.920886
3  G0100010  2013      26.763541
4  G0100010  2012      29.304187

In [3]:
drought_5year = pd.read_csv(r'../data/drought_monitor/drought_indicator_5year_matrics_reformat.csv')
drought_5year.head()

    GISJOIN  year  drought_5year
0  G0100010  2016       6.920886
1  G0100010  2015      26.763541
2  G0100010  2014      29.970673
3  G0100010  2013      29.970673
4  G0100010  2012      56.162279

In [4]:
lookup_table = pd.read_csv(r'../data/county_ID_lookup_table.csv')
lookup_table.head()

,STATEFP10,COUNTYFP10,STATE_NAME10,COUNTY_NAME10,NAMELSAD10,GISJOIN
0,2,13,Alaska,Aleutians East,Aleutians East Borough,G0200130
1,2,16,Alaska,Aleutians West,Aleutians West Census Area,G0200160
2,28,107,Mississippi,Panola,Panola County,G2801070
3,28,101,Mississippi,Newton,Newton County,G2801010
4,28,27,Mississippi,Coahoma,Coahoma County,G2800270

In [5]:
final = mortality.merge(drought_3year, left_on=['GISJOIN','year'], right_on=['GISJOIN','year'], how='inner')
final = final.merge(drought_5year, left_on=['GISJOIN','year'], right_on=['GISJOIN','year'], how='inner')
final = final.merge(lookup_table,on = 'GISJOIN',how = 'inner')
final.to_csv(r'../data/data_combined.csv')

In [6]:
final.head()

,GISJOIN,year,deaths_65+_b,rate_crd_65+_b,rate_adj_65+_b,deaths_u5_b,rate_crd_u5_b,rate_adj_u5_b,deaths_all_b,rate_crd_all_b,rate_adj_all_b,drought_3year,drought_5year,STATEFP10,COUNTYFP10,STATE_NAME10,COUNTY_NAME10,NAMELSAD10
0,G0100010,2004,254,4894.0,5492.7,NaN,NaN,NaN,377,779.5,934.5,0.922944,33.055951,1,1,Alabama,Autauga,Autauga County
1,G0100010,2005,307,5713.8,6686.2,NaN,NaN,NaN,454,913.9,1123.4,0.000000,3.892085,1,1,Alabama,Autauga,Autauga County
2,G0100010,2006,298,5255.7,6168.0,NaN,NaN,NaN,457,890.4,1073.1,8.999964,9.922908,1,1,Alabama,Autauga,Autauga County
3,G0100010,2007,263,4495.0,5145.9,NaN,NaN,NaN,406,774.7,906.7,43.713397,43.713397,1,1,Alabama,Autauga,Autauga County
4,G0100010,2008,309,5102.4,5704.7,10,NaN,NaN,457,857.8,975.4,70.571489,70.571489,1,1,Alabama,Autauga,Autauga County