Author: Yang
Date: 04/22/2016

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
plt.style.use('ggplot')

In [2]:
county_area = pd.read_csv(r"..\..\data\drought_monitor\county_area.csv")
county_area.head()

    GISJOIN         AREA           X          Y
0  G0200130  7032.737436 -161.993658  55.363561
1  G0200160  4404.152728 -107.656871  52.808638
2  G2801070   705.131640  -89.950567  34.363935
3  G2801010   579.601937  -89.118809  32.400232
4  G2800270   583.152399  -90.602687  34.229166

In [28]:
dirs = os.listdir(r"..\..\code\analysis_stage1\coefficients")
combined = pd.DataFrame()
combined = county_area*1
combined.rename(columns ={'GISJOIN':'countyID'},inplace = True)
combined.head()

   countyID         AREA           X          Y
0  G0200130  7032.737436 -161.993658  55.363561
1  G0200160  4404.152728 -107.656871  52.808638
2  G2801070   705.131640  -89.950567  34.363935
3  G2801010   579.601937  -89.118809  32.400232
4  G2800270   583.152399  -90.602687  34.229166

In [29]:
for file in dirs:
    name = file.split('_')[-1].split('.')[0]
    print(name)
    coeff = pd.read_csv(r"..\..\code\analysis_stage1\coefficients\%s"%file)[['countyID','coeff']]
    coeff.rename(columns ={'coeff':'coeff%s'%name},inplace = True)
    combined = combined.merge(coeff,on='countyID

r12p13
r12p14
r12p15
r24p13
r24p14
r24p15
r25p13
r25p14
r25p15
r26p13
r26p14
r26p15
r27p13
r27p14
r27p15
r6p13
r6p14
r6p15

In [31]:
combined.head()

,countyID,AREA,X,Y,coeffr12p13,coeffr12p14,coeffr12p15,coeffr24p13,coeffr24p14,coeffr24p15,...,coeffr25p15,coeffr26p13,coeffr26p14,coeffr26p15,coeffr27p13,coeffr27p14,coeffr27p15,coeffr6p13,coeffr6p14,coeffr6p15
0,G2801070,705.131640,-89.950567,34.363935,-2.193952,-11.942805,-2.252574,-0.165308,0.050538,-0.235138,...,-0.129977,0.305088,0.598017,1.269316,0.000000,0.000000,0.000000,-18.576781,-9.786884,-4.062665
1,G2801010,579.601937,-89.118809,32.400232,-4.267973,-4.173735,-13.246022,-0.047950,0.066027,-0.246924,...,-4.578429,0.741259,1.172135,1.493848,0.000000,0.000000,0.000000,-4.937798,16.569964,-6.983787
2,G2800270,583.152399,-90.602687,34.229166,-0.996047,-0.502867,-6.917996,-0.007981,0.014613,-0.042842,...,-0.109401,0.380833,0.480841,1.237048,0.000000,0.000000,0.000000,-13.578317,22.951143,75.925763
3,G2200650,650.899650,-91.242583,32.364403,-5.849557,-3.678441,-7.271064,0.107410,0.085370,0.120780,...,-0.867019,-0.123029,0.001603,0.018826,0.001799,0.003793,0.000512,-42.042681,-32.596140,-55.221417
4,G4801130,908.613864,-96.777875,32.766631,-0.251797,-1.261764,-0.283436,-0.010271,0.012755,-0.038838,...,-0.264745,0.312301,0.231084,-0.287459,0.131471,0.155739,0.159292,-5.960473,-13.081493,-7.346469

In [ ]:
%matplotlib inline
ax = combined.plot(x='X',y='Y',kind ='scatter',c = combined['coeff'],cmap = 'jet',vmin=-20, vmax=20,figsize = (20,10),edgecolors ='None')